### ISSUE TITLE
Please help to Evaluate "Computer programming for everyone" on Futurelearn to replace py4e in "Intro CS"

### ISSUE THREAD

**Issue by krishnakumarg1984** [ossu/computer-science#785] opened 2020-09-12 17:27 UTC
The "Intro to CS" section currently recommends "Python for Everybody", which I have taken. Py4e is a fairly long course, which sorts of eats into your time in advancing through the curriculum, which can sap one's motivation especially at such an early stage (before any real CS is undertaken).

I am proposing an evaluation of an alternative: [FutureLearn's Computer Programming for Everyone]("https://www.futurelearn.com/courses/computer-programming-for-everyone"), which might be a decent replacement, and help to keep the motivation levels high by moving faster through the curriculum.  Having taken FutureLearn's pre-calculus course myself (an OSSU prerequisite), I wish to reaffirm that their catalogue contains material that is nothing to be scoffed at.

Can the moderators take a look, and offer your thoughts on whether it is worth replacing py4e as the intro course?

**Comment by Alaharon123** [comment] 2020-09-12 18:42
This is actually the same course as the one we currently use as stated at https://www.py4e.com . The questions to ask are whether we need all five Coursera courses in the curriculum and, if we only need the first one or two, which of the four websites should be the primary one linked

**Comment by krishnakumarg1984** [comment] 2020-09-12 19:18
@Alaharon123 Not at all. This is a different put together by the Institute of Coding and hosted on FutureLearn.

Please have a look here. [Computer Programming for Everyone] (https://www.futurelearn.com/courses/computer-programming-for-everyone). It has no connection with Py4E.

**Comment by Alaharon123** [comment] 2020-09-12 22:04
Oh my bad, I misread it as Python for Everybody, which is also on FutureLearn

**Comment by Alaharon123** [comment] 2020-09-12 22:12
Taking a glance, it appears to use Scratch or something similar. The primary purpose of Intro Programming is to have something that teaches Python slower than Intro CS so people who've never touched a programming language don't get left behind by the fast pace of the Intro CS course. I don't think Programming for Everyone meets that goal. However if the problem is how long Py4e is, it could be worth cutting down on how much of it we include as an alternate solution to that problem. Do you think Programming for Everyone would be a better solution? Make a case for it.

**Comment by krishnakumarg1984** [comment] 2020-09-14 01:51
I have taken "py4e" and it took me a fairly long time to finish all 5 courses about 1.5 months)

I don't want to get into a "Language A" vs "Language B" discussion, but before the intro CS stage, does it matter that they use scratch, as long as the concepts of programming are covered.  If using scratch was a demerit, then PL A,B & C shouldn't be in the curriculum since theese courses use "RacketML" I believe?

The institute of coding has received tremendous attention in the UK these days, and they have been registering/enrolling attendees by the droves.  The course is only 2 weeks long, and might help to keep the motivation levels for new beginners. 

Can we recommend this as an "alt"?  OSSU caters to a much wider audience spanning the entire spectrum ranging from:

* full-time CS students who use the curriculum over 3-4 years to regularly supplement what they learn at their local universities, 

all the way to

* single dads with non-technical education who have been furloughed or out of jobs, looking to learn CS skills part-time from home juggling life and family

and everything in between.  Including a shorter "alt" course for those pressed for time (especially if we meet the CS2013 curriculum standards) could be worth considering.

**Comment by StevenKJo** [comment] 2020-09-14 05:53
I agree with you, [py4e](https://py4e.com) its a long course for an introductory course. [Computing Programming for Everyone](https://www.futurelearn.com/courses/computer-programming-for-everyone "UMich edx.org") that you recommended lowers the bar of skill for a student to start because its pretty short and simple, like [CS50s week 0 Scratch](https://cs50.harvard.edu/x/2020/weeks/0/). I think [CS50's Understanding Technology](https://www.edx.org/course/cs50s-understanding-technology) does the satisfies the same objective, its [CS50](https://cs50.harvard.edu/x/2020/) prequel and its a bit more complete. Thanks to this issue i adjusted my curriculum draft, if i started the curriculum again i would have done it like this. 

my draft of [comment-660886018](https://github.com/ossu/computer-science/issues/751#issuecomment-660886018)

---

## Intro CS
**Knowledge Areas**: `SDF - Software Development Fundamentals`

If you've never written a for-loop, start here. Students who have been introduced to programming should also take this course for a flavor of the material to come. If you finish the course wanting more, Computer Science is likely for you!

| KA | **Course** | **Hours**| **Optional Resources** |**Prerequisites** |
|---|---|---|---|---|
| `SDF`|[CS50's Understanding Technology](https://www.edx.org/course/cs50s-understanding-technology "Harvard edx.org ") | 24 |[Computing Programming for Everyone](https://www.futurelearn.com/courses/computer-programming-for-everyone "University of Leeds futurelearn.com") | none

## Core CS
### Theory
**Knowledge Areas**: `SDF - Software Development Fundamentals` `SP - Social Issues and Professional Practice` `DS - Discrete Structures` `PL - Programming Languages` `AL - Algorithms and Complexity` `CN - Computational Science`
> *Objective*: Develop effective ways to solve computing problems.

| KA | **Course** | **Hrs** | **Optional Resources** | **Prerequisites** |
|---|---|---|---|---|
| `SDF`| [Python for Everbody](https://www.py4e.com "UMich") | 102 | [Intro](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-10 "MIT mit.edu"), [Fundamentals](https://www.coursera.org/specializations/computer-fundamentals "RICEx edx.org"), [Basics](https://www.edx.org/course/programming-basics-iitbombayx-cs101-1x), [khan](https://www.khanacademy.org/computing/computer-programming/programming), [Java](https://www.coursera.org/specializations/java-programming), [GT](https://www.edx.org/professional-certificate/introduction-to-python-programming), [100+](https://github.com/ProgrammingHero1/100-plus-python-coding-problems-with-solutions "100 Plus Python Coding Problems With Solutions")| none
| `SDF`| [Intro to CS - CS50](https://www.edx.org/course/introduction-computer-science-harvardx-cs50x#! "Harvard edx.org ") | 132 | [Missing](https://missing.csail.mit.edu/ " MIT mit.edu"), [Code 1](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x "UBCx edx.org") [2](https://www.edx.org/course/how-code-complex-data-ubcx-htc2x "UBCx edx.org") [Book](https://htdp.org/2003-09-26/), [IT](https://www.coursera.org/learn/technical-support-fundamentals?specialization=google-it-support#syllabus),  [Law](https://cs50.harvard.edu/law/2019), [Business](https://cs50.harvard.edu/business/2017/), [Web](https://cs50.harvard.edu/web/2020/) | [algebra](https://www.khanacademy.org/math/algebra-home)
| `SP`|  [Learning How to Learn](https://www.coursera.org/learn/learning-how-to-learn "McMaster coursera.org") | 15 | [Mindshift](https://www.coursera.org/learn/mindshift) | none
| `DS`|  [<sup>1</sup>](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf "CS curriculums use calculus not as a means for domain knowledge, but more as a method for helping develop mathematical maturity and clarity of mathematical thinking to have the basis on which to then build CS-specific mathematics.") [Calculus A](https://www.edx.org/course/calculus-1a-differentiation "MIT edx.org") [B](https://www.edx.org/course/calculus-1b-integration) [C](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series) & [Prob.](https://projects.iq.harvard.edu/stat110/home "Harvard edx.org ") | 256 | [Calculus K](https://www.khanacademy.org/math/high-school-math/precalculus) [B](https://brilliant.org/calculus/), [Probability MIT](https://www.edx.org/course/introduction-probability-science-mitx-6-041x-2 "MIT edx.org ") [K](https://www.khanacademy.org/math/statistics-probability/probability-library) [B](https://brilliant.org/discrete-mathematics/) | [high school](https://www.khanacademy.org/math/high-school-math)
| `DS` |[Mathematics for CS](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/index.htm "MIT ocw.mit.edu")| 65 | [Discrete](https://www.coursera.org/specializations/discrete-mathematics), [Logic](https://www.coursera.org/learn/logic-introduction "Stanford coursera.org"), [Effective](https://www.edx.org/course/effective-thinking-through-mathematics-utaustinx-ut-9-01x-0), [Thinking](https://www.coursera.org/learn/mathematical-thinking), [Sets](https://www.youtube.com/playlist?list=PL5KkMZvBpo5AH_5GpxMiryJT6Dkj32H6N) |  [Calculus A](https://www.edx.org/course/calculus-1a-differentiation "MIT edx.org") [B](https://www.edx.org/course/calculus-1b-integration) [C](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series)
| `PL`| [PL Part A](https://www.coursera.org/learn/programming-languages "UW coursera.org") [Part B](https://www.coursera.org/learn/programming-languages-part-b "UW coursera.org") [Part C](https://www.coursera.org/learn/programming-languages-part-c "UW coursera.org")| 66 | [Rosalind](http://rosalind.info/problems/locations/), [Book 1](http://cs.brown.edu/~sk/Publications/Books/ProgLangs/), [Book 2](https://papl.cs.brown.edu/2018/), [Projects](https://github.com/MunGell/awesome-for-beginners) | `SDF` , [Instructor's](https://www.coursera.org/lecture/programming-languages/recommended-background-k1yuh)
| `AL` | [Algorithms](https://www.coursera.org/specializations/algorithms "Stanford coursera.org") | 96 | [Khan](https://www.khanacademy.org/computing/computer-science/algorithms), [UCSD](https://www.coursera.org/specializations/data-structures-algorithms), [Algo](https://visualgo.net), [freecodecamp](https://www.freecodecamp.org),<br /> [geeksforgeeks](https://www.geeksforgeeks.org/fundamentals-of-algorithms/), [Princeton 1](https://www.coursera.org/learn/algorithms-part1) [2](https://www.coursera.org/learn/algorithms-part2), [MIT 1](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/index.htm) [2](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-design-and-analysis-of-algorithms-spring-2015/index.htm)|`SDF` `PL` `DS`
| `CN` |  [Computation](http://aduni.org/courses/theory/index.php?view=cw), [videos](https://www.youtube.com/watch?v=FeT7iohSsPA&list=PLTke5lHMAdSNmi57H0DOTzClHPK6UwSTN&index=2&t=0s "aduni.org youtube.com")|  80 |[Princeton](https://www.coursera.org/learn/cs-algorithms-theory-machines), [Intro Book](https://www.amazon.com/Introduction-Theory-Computation-Michael-Sipser/dp/113318779X) |`DS` `AL`

**Comment by krishnakumarg1984** [comment] 2020-09-16 01:59
errr... before we amend the curriculum, shouldn't someone take the FutureLearn programming course, and offer some feedback?

**Comment by rayhendricks** [comment] 2020-09-16 02:25
I signed up for the precancerous course but they want you to pay to take tests. This is kinda annoying so yes I do agree that khan academy math 1-3 is better as ray is free

**Comment by krishnakumarg1984** [comment] 2020-09-16 03:15
@rayhendricks Please stay on topic when commenting

What do you mean by "precancerous" course?  This issue is not about any math course, but about "introduction to programming".

**Comment by waciumawanjohi** [comment] 2020-09-16 03:38
I think it may have been an auto-correct of pre-calculus, which would make sense with the reference to Khan Academy's Math 1-3.

**Comment by krishnakumarg1984** [comment] 2020-09-17 03:00
@waciumawanjohi Which original message are you referring to? This issue specifically deals with evaluating an alternative 'Intro to programming' courses and has nothing to do with Maths.  Maths & pre-calculus related discussions may happen elsewhere outside of this issue.

**Comment by waciumawanjohi** [comment] 2020-09-17 03:27
In your first message above you wrote
> Having taken FutureLearn's pre-calculus course myself (an OSSU prerequisite)
, I wish to reaffirm that their catalogue contains material that is nothing to be scoffed at.

I think that's what the other contributor was responding to. Hopefully he will return and either explain or move the comment to the proper issue.

**Comment by rachel83az** [comment] 2020-09-17 12:59
> Before we amend the curriculum, it would be nice if someone can take the FutureLearn programming course and offer some feedback.

I've had this in my "todo list" at FutureLearn for a while. The "first week" tells you what computers do and introduces you to the concept of what a program is without introducing any code. 

Week 2 starts by introducing you to https://blockly.games/ You are instructed to do Maze first, then Turtle. 

It then moves on to discuss programming as part of a team (a very basic overview), skills that employers are looking for (again, very basic), more teamwork, career advice, finished.

The test at the end does not cost money to do. It is vaguely useful, but not overly so. It took me about 15 minutes to go through the course (not counting Blockly - I already did this in my uni course). I imagine it would only take a day or two for someone completely ignorant of computer programming to finish. I am not sure that this adds value to the OSSU curriculum.

**Comment by StevenKJo** [comment] 2020-09-17 19:54
@krishnakumarg1984 you are right in the amount of time Intro CS takes right now, longer courses can be moved to Core CS. What do you think about the [CS50's Understanding Technology](https://www.edx.org/course/cs50s-understanding-technology) ?

Proposed Intro CS:

|**Total Hours**|**24**|
|---|---|
| [CS50's Understanding Tech.](https://www.edx.org/course/cs50s-understanding-technology "Harvard edx.org ") [alt](https://cs50.harvard.edu/technology/2017/)  | 24 |

Current Intro to CS:
|**Total Hours**|**261**|
|---|---|
| [Python for Everbody](https://www.py4e.com "UMich") | 102 |
| [Intro to CS and Programming](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-10 "MIT mit.edu") | 135|
|[Missing Semester](https://missing.csail.mit.edu/ " MIT mit.edu")| 24|

**Comment by krishnakumarg1984** [comment] 2020-09-17 19:57
Missing semester is definitely not an intro to CS. it's an intro to practical IT required as an adjunctb life companion for a CS (read programming) career.


I haven't taken CS50, but the past comments here in the issues of this repo suggests a mixed view.

**Comment by StevenKJo** [comment] 2020-09-17 20:02
@krishnakumarg1984 its not [CS50](https://cs50.harvard.edu/x/2020/) that takes 144 hours to complete, its  [CS50's Understanding Technology](https://www.edx.org/course/cs50s-understanding-technology) that takes 24 hours to complete. Its the short and simple prequel that people can course it like a trailer before committing to the full curriculum.

**Comment by krishnakumarg1984** [comment] 2020-09-17 20:11
I see. At about 3 hours/week effort, it will take 8 weeks (2 months).   Maybe that's reasonable. If the content is exciting to a beginner, probably that's enough to keep them engaged.

I am a beginning student of OSSU. I haven't taken CS50. if others have taken it and it's deemed good, and 2 months seem appropriate, then maybe it's a good choice.

**Comment by rachel83az** [comment] 2020-09-17 20:58
CS50 - understanding technology:

1. **Hardware** Video is about 1 hour long. Covers binary, basics of ASCII, basics of hardware. 1st assignment asks you to do things like explain the different types of memory, convert binary, know what a USB device is.
2. **Internet**  Video is just over 50 minutes long. Basics of what the internet means. Assignment asks you to explain what certain IP addresses mean, describe difference between access points, firewalls, etc. Define DCHP/DNS/IP address/packet. http vs https.
3. **Multimedia** Video is 40 minutes long. What are file formats? Difference between different file formats. What "bits" mean in graphical formats. How videos work.
4. **Security**  Video is over an hour long. Cookies. Password security. Why certain passwords are insecure. VPNs.
5. **Web development** Video is over an hour long. HTML vs. CSS. Assignment asks you to create a basic website at repl.it. 
6. **Programming** Video is over an hour long. Assignment is to create a very basic Scratch program/video/animation/game at https://scratch.mit.edu/ using https://scratch.mit.edu/ideas as a resource.

**Comment by waciumawanjohi** [comment] 2020-09-17 21:32
[From this comment](https://github.com/ossu/computer-science/issues/785#issuecomment-694256852), it seems like the original poster is satisfied that the issue that was opened has been addressed. Closing this issue. Users are welcome to continue discussion of anything else that they desire in this thread. If there is desire for some other change to the curriculum, feel free to open a new issue.

**Closed by waciumawanjohi** 2020-09-17 21:32 UTC
