### ISSUE TITLE
Why you removed me and changed my access in OSSU organization?

### ISSUE THREAD

**Issue by ericdouglas** [ossu/computer-science#784] opened 2020-09-11 23:59 UTC
@waciumawanjohi today I received several emails from GitHub because I was removed from almost all OSSU teams.

Someone also changed my access to `member`, and as a founder of OSSU organization and OSSU-CS I think it was really disrespectful since I was not even contacted before.

![image](https://user-images.githubusercontent.com/4119931/92981723-7f278680-f471-11ea-9333-b4a0177da7a4.png)

I would like to have my access restored to owner again.

Thanks.

cc @hanjiexi

**Comment by amorriscode** [comment] 2020-09-12 02:30
@ericdouglas I know that the OSSU cohort group was removed, which was planned, but it's absolutely wrong for your access to be taken away. 😞

**Comment by ericdouglas** [comment] 2020-09-16 09:02
@amorriscode thanks for your support, I really appreciate it.

@waciumawanjohi was you that changed my role in the organisation? 

This situation is going out of control in the disrespect that is happening to me.

4 days without an answer, and activity are happening in the repository, people are being added to the organisation...

I'm extremely disappointed with all this. This is completely wrong.

Would someone watching this repo help me to change this? I would really appreciate because it is really affecting me.

Thanks again.

**Comment by amorriscode** [comment] 2020-09-16 12:12
@ericdouglas dropped a message to @waciumawanjohi on the Discord, hopefully that brings visibility to this sooner.

**Comment by WybeTuring** [comment] 2020-09-16 14:12
Hopefully, it does. This is quite disrespectful.

**Comment by waciumawanjohi** [comment] 2020-09-16 15:54
Hi Eric,
You are correct, last week I was making changes to the Github project to match permissions to the roles that individuals currently have. Part of this was prompted by the number of repos that we have that are functionally abandoned. For example, earlier this year the 'Help' repo received an awesome Issue from a first time contributor laying out an almost complete math curriculum. It's something that I wish OSSU could have responded to within hours. Instead, it was months before we did. The root cause was that permissions and notifications had not been updated to match the individuals putting in daily work for OSSU.

You mentioned that you found it disrespectful that we didn't contact you. I apologize that you and other individuals whose GitHub roles were changed were not contacted beforehand. I realize now that failing to contact you beforehand likely made it a surprise. I want to assure you that regardless of what administrative changes we make, the leadership of OSSU is continuing to feature your role as the founder.

At the same time, you stated publicly that you were setting up others as the leaders of OSSU. In the years since that announcement, the installed leaders have made changes, including bringing on other new leaders. Some have even formally stepped down themselves. And in those 2 and a half years (half the life of this 5 year old project) you have not participated in any of the public discussions or modifications to OSSU. 

We certainly want to honor the contributions that you made to OSSU. When you stepped down, I thanked you publicly for shepherding the project. I praised your judgement in choosing successors who had demonstrated leadership in the organization. You are listed as founder of OSSU in the CS repo, a page thats been seen by hundreds of thousands of people. We honor and respect your contribution.

I am closing this issue since it does not pertain to modifying the CS curriculum, but feel free to reach out to @hanjiexi or me with any questions or concerns.

**Closed by waciumawanjohi** 2020-09-16 15:54 UTC

**Comment by ericdouglas** [comment] 2020-09-16 16:16
@waciumawanjohi what you did is absolutely out of your scope to act, you are not allowed to change my permission in this organization.

There is absolutely no reason in doing this, and I want to have my access restored to owner again.

Serious, you are doing a lot of harm to me removing my access from the organization I created. This is absolutely insane.

I want to ask again for contributors of this project and students to manifest your thoughts about this absurd situation.

**Comment by chygrynskiy** [comment] 2020-09-16 16:57
@Eric I feel you man

**Comment by StevenKJo** [comment] 2020-09-16 23:16
I have been doing OSSU's recommended CS courses for more less two years without commenting since I wanted to be more knowledgeable on the curriculum before criticizing. Yet I just recently started discussing and reading more on the curriculum instead of just following it blindly. 

Reading @waciumawanjohi almost daily active helpful contributions to peoples comments and discussing with him and the community has definitely helped me in a great positive way on understanding my CS path. However I don't see why the founder of OSSU has to have his permissions removed, founding an organization its usually seen as the biggest contribution inside most organizations.

Btw @ericdouglas can you constructively criticize my curriculum draft posted on [comment-660886018](https://github.com/ossu/computer-science/issues/751#issuecomment-660886018).

Thanks in advance!


*Preview:*

---

## Intro CS
**Knowledge Areas**: `SDF - Software Development Fundamentals`

If you've never written a for-loop, start here. Students who have been introduced to programming should also take this course for a flavor of the material to come. If you finish the course wanting more, Computer Science is likely for you!

| KA | **Course** | **Hours**| **Optional Resources** |**Prerequisites** |
|---|---|---|---|---|
| `SDF`|[CS50's Understanding Tech.](https://www.edx.org/course/cs50s-understanding-technology "Harvard edx.org ") [alt](https://cs50.harvard.edu/technology/2017/) | 24 |[Programming for Everyone](https://www.futurelearn.com/courses/computer-programming-for-everyone "University of Leeds futurelearn.com") | none

## Core CS
### Theory
**Knowledge Areas**: `SDF - Software Development Fundamentals` `SP - Social Issues and Professional Practice` `DS - Discrete Structures` `PL - Programming Languages` `AL - Algorithms and Complexity` `CN - Computational Science`
> *Objective*: Develop effective ways to solve computing problems.

| KA | **Course** | **Hrs** | **Optional Resources** | **Prerequisites** |
|---|---|---|---|---|
| `SDF`| [Python for Everbody](https://www.py4e.com "UMich") | 102 | [Intro](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-10 "MIT mit.edu"), [Fundam.](https://www.coursera.org/specializations/computer-fundamentals "RICEx edx.org"), [Basics](https://www.edx.org/course/programming-basics-iitbombayx-cs101-1x), [khan](https://www.khanacademy.org/computing/computer-programming/programming), [Java](https://www.coursera.org/specializations/java-programming), [GT](https://www.edx.org/professional-certificate/introduction-to-python-programming), [100+](https://github.com/ProgrammingHero1/100-plus-python-coding-problems-with-solutions "100 Plus Python Coding Problems With Solutions")| none
| `SDF`| [Intro to CS - CS50](https://www.edx.org/course/introduction-computer-science-harvardx-cs50x#! "Harvard edx.org ") | 144 | [Missing](https://missing.csail.mit.edu/ " MIT mit.edu"), [Code 1](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x "UBCx edx.org") [2](https://www.edx.org/course/how-code-complex-data-ubcx-htc2x "UBCx edx.org") [Book](https://htdp.org/2003-09-26/), [IT](https://www.coursera.org/learn/technical-support-fundamentals?specialization=google-it-support#syllabus),  [Law](https://cs50.harvard.edu/law/2019), [Business](https://cs50.harvard.edu/business/2017/)| none
| `SP`|  [Learning How to Learn](https://www.coursera.org/learn/learning-how-to-learn "McMaster coursera.org") | 15 | [Mindshift](https://www.coursera.org/learn/mindshift) | none
| `DS`|  [<sup>1</sup>](https://www.acm.org/binaries/content/assets/education/cs2013_web_final.pdf "CS curriculums use calculus not as a means for domain knowledge, but more as a method for helping develop mathematical maturity and clarity of mathematical thinking to have the basis on which to then build CS-specific mathematics.") [Calculus A](https://www.edx.org/course/calculus-1a-differentiation "MIT edx.org") [B](https://www.edx.org/course/calculus-1b-integration) [C](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series) & [Prob.](https://projects.iq.harvard.edu/stat110/home "Harvard edx.org ") | 256 | [Calculus K](https://www.khanacademy.org/math/high-school-math/precalculus) [B](https://brilliant.org/calculus/), [Probability MIT](https://www.edx.org/course/introduction-probability-science-mitx-6-041x-2 "MIT edx.org ") [K](https://www.khanacademy.org/math/statistics-probability/probability-library) [B](https://brilliant.org/discrete-mathematics/) | [high school](https://www.khanacademy.org/math/high-school-math)
| `DS` |[Mathematics for CS](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/index.htm "MIT ocw.mit.edu")| 65 | [Discrete](https://www.coursera.org/specializations/discrete-mathematics), [Logic](https://www.coursera.org/learn/logic-introduction "Stanford coursera.org"), [Effective](https://www.edx.org/course/effective-thinking-through-mathematics-utaustinx-ut-9-01x-0), [Thinking](https://www.coursera.org/learn/mathematical-thinking), [Sets](https://www.youtube.com/playlist?list=PL5KkMZvBpo5AH_5GpxMiryJT6Dkj32H6N) |  [Calculus A](https://www.edx.org/course/calculus-1a-differentiation "MIT edx.org") [B](https://www.edx.org/course/calculus-1b-integration) [C](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series)
| `PL`| [PL Part A](https://www.coursera.org/learn/programming-languages "UW coursera.org") [Part B](https://www.coursera.org/learn/programming-languages-part-b "UW coursera.org") [Part C](https://www.coursera.org/learn/programming-languages-part-c "UW coursera.org")| 66 | [Rosalind](http://rosalind.info/problems/locations/), [Book 1](http://cs.brown.edu/~sk/Publications/Books/ProgLangs/), [Book 2](https://papl.cs.brown.edu/2018/), [Projects](https://github.com/MunGell/awesome-for-beginners), [Web](https://cs50.harvard.edu/web/2020/) | [algebra](https://www.khanacademy.org/math/algebra-home) | `SDF` , [Instructor's](https://www.coursera.org/lecture/programming-languages/recommended-background-k1yuh)
| `AL` | [Algorithms](https://www.coursera.org/specializations/algorithms "Stanford coursera.org") | 96 | [Khan](https://www.khanacademy.org/computing/computer-science/algorithms), [UCSD](https://www.coursera.org/specializations/data-structures-algorithms), [Algo](https://visualgo.net), [freecodecamp](https://www.freecodecamp.org),<br /> [geeksforgeeks](https://www.geeksforgeeks.org/fundamentals-of-algorithms/), [Princeton 1](https://www.coursera.org/learn/algorithms-part1) [2](https://www.coursera.org/learn/algorithms-part2) [Book](https://algs4.cs.princeton.edu/home/), [MIT 1](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/index.htm) [2](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-design-and-analysis-of-algorithms-spring-2015/index.htm)|`SDF` `PL` `DS`
| `CN` |  [Computation](http://aduni.org/courses/theory/index.php?view=cw), [videos](https://www.youtube.com/watch?v=FeT7iohSsPA&list=PLTke5lHMAdSNmi57H0DOTzClHPK6UwSTN&index=2&t=0s "aduni.org youtube.com")|  80 |[Princeton](https://www.coursera.org/learn/cs-algorithms-theory-machines), [Intro Book](https://www.amazon.com/Introduction-Theory-Computation-Michael-Sipser/dp/113318779X) |`DS` `AL`

...

**Comment by hanjiexi** [comment] 2020-09-17 00:00
Hi Eric,

Let me give you some context so that you can hopefully understand better what's going on: in the time since you've stepped away, OSSU has grown significantly larger. The volume of students and active contributors has been growing steadily since I became a maintainer, to the point where I couldn't do it myself and appointed Waciuma as co-maintainer two years ago; later, OSSU's activity *exploded* around the time the pandemic hit, since everyone started doing online courses. The people who are actively working on OSSU have become utterly indispensible in managing what is now a highly complex social structure with short-term needs and long-term expectations.

To manage this growth and protect it from current and future threats, OSSU is now governed by a board of directors. This board handles legal/administrative stuff behind the scenes, while the community-first approach remains in place for its daily operations. As an example of a threat, recently we were contacted by an organization that appears to be a diploma mill and may be committing fraud. On a few days notice, and without permission from the board, this organization created a website asking students to pay them for a degree in partnership with Open Source Society University. This puts OSSU and all of the work that contributors have done at risk. It's the responsibility of the board to handle such a situation, to research those who want to partner with OSSU and to stop organizations who want to profit crookedly from the OSSU name.

To bring this back to the issue, what the board has decided to do is standard practice in organizations: when a leader steps down, they relinquish their leadership rights, including any authority for making decisions for the organization or the ability to represent the organization, as well as any administrative access they may have had. The former prevents many an awkward situation; the latter is basic cybersecurity.

It has been a long time since you disengaged from OSSU. You will always be OSSU's founder — no one can take that away from you — but we've got to move on and forward. Therefore, I have to disagree that this is an absurd situation. I would instead argue that it would be exceedingly odd and irresponsible if the new management of an organization *didn't* shut down the former manager's administrative access. Notifying the former manager of such routine procedures is unnecessary; for instance, if I left OSSU, I wouldn't expect an email requesting permission to shut down my access. On the contrary, I think it would be quite strange if I did receive such an email.

You mentioned that this is causing you harm, but it's unclear to me what this harm is. The only change that has occurred is on the backend: you no longer have the ability to create/edit/delete repositories/teams and add/remove members from the GitHub organization/teams. I don't see why these would be of interest to you, and in any case, with the formalization of OSSU's governance and community-oriented processes, we can't allow people who aren't involved with OSSU to make major administrative changes without going through the proper procedures of board approval or community buy-in, as appropriate. Like anyone else, you can still contribute when you find the time and take part in discussions about the curriculums, virtually all of which are public. If you're interested in starting a new curriculum, nothing prevents you from going through the same process that we all go through: engagement with the community.

I hope you would agree that OSSU moving forward with a formal organizational governance is the best next step, and that such board needs to do what every responsible board does to put our affairs in order. *Absolutely no disrespect was intended.* We still admire you for making the brazen claim that you can get a free college-level education in computer science for free, and jumpstarting a community and curriculum to make this a reality. As founder, you are of course welcome to set up a meeting with us to discuss anything you wish. But I must emphasize that we, as the board, cannot reinstate your GitHub account to that of an Owner of the OSSU GitHub organization simply because you founded the repo some years ago. There would have to be a reason for it that can be formally justified to support the organization's operations or meet its administrative requirements.

I hope you can understand. Thank you for taking the time to read this long post.

Regards,
hanjiexi

**Comment by ericdouglas** [comment] 2020-09-17 11:20
@StevenKJo thanks for your support and it looks very interesting your draft indeed!

**Comment by ericdouglas** [comment] 2020-09-17 11:32
@hanjiexi when I give you the `owner` level access, it was to you manage OSSU-CS more comfortably, with ability to add people and create repositories and stuff like that.

It was never conceded to you permission to remove/change my access in the future. This is absolutely wrong. OSSU organization is very different from OSSU-CS. You removed my access to OSSU organization AND OSSU-CS without even contact me. This is not right at all.

I really regret to have conceded to you this access level, but I never imagined that something like this would occur. This is an act of treason.

I learned the lesson in the worst possible way.

**Comment by robbrit** [comment] 2020-09-17 15:18
Going to chime in here as a semi-neutral third party, since despite being an active member of the Discord/Gitter side of OSSU for the last few years, I didn't know who Eric was until this thread started.

Here's what it looks like from my perspective:
1. Eric handed over the reins for OSSU and then disappeared from it. Like I said, I didn't know who he was, and I doubt many of the currently active members in the community do either. There's even a [Hacker News](https://news.ycombinator.com/item?id=11134781) post from _2016_ wondering where he went.
    * Nothing wrong with this at all, it's not only normal for changes in leadership to happen, it's necessary for the survival of an organization. People move on, but an organization still needs people to manage it and put in the work.
1. OSSU continued on without him with @hanjiexi and @waciumawanjohi carrying the torch.
1. Several years later, in accordance with the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege), Waciuma removed admin access to the Github repo for anybody who didn't need it.
1. Eric shows up after years of absence angrily declaring that OSSU belongs to him and demands access back.

The way I see it, this is purely a political battle.

While I appreciate the contribution Eric made in getting this ball rolling, I'd definitely side with waciuma and hanjiexi on this one. Giving Eric his access back would send a clear message that OSSU values politics over security and good governance, which is not something that as an engineer I can get behind.

**Comment by amorriscode** [comment] 2020-09-17 15:29
While I do this it's unfortunate how this came about, after hearing both sides and thinking it through further, I do think it makes sense. I'm extremely happy the OSSU is picking up steam. I'm glad there is an organization being developed. I think it could truly help shape how education is consumed in the future.

For security reasons, I think the admin access makes sense. How can an organization function when somebody could destroy all of their work in the middle of the night without a moments notice? Eric is still a member of the organization, just not an administrator.

I wish Eric was notified earlier but he has been absent and _a lot_ has happened without it. The project itself likely looks very different than it did when Eric was last involved. I imagine that, if he chose to be involved again in the future, he would be welcomed with open arms.

**Comment by ericdouglas** [comment] 2020-09-17 17:09
There is more to this situation than people know. 

My absence for this long period had several reasons (did someone thought about it?), and one of them is directly related to behaviour of current and past members in the organization along the time that made me loose motivation to keep contributing.

Despite all of this, I genuinely appreciate every single person that commented in this issue, for real.

I did not invite more people to give opinion here to necessarily do this in my favour, I wanted to hear what you thought about all this situation, independently which opinion is yours.

All this problem that happened to me was derived from my own action (give owner access to others), so I know I am responsible for all this.

I did not change my opinion about what happened, but that's it.

So I finish my participation in this issue.

Thanks again for every person that replied here, regardless of your opinion, you truly helped me a lot.
