### ISSUE TITLE
Hack the kernel is down

### ISSUE THREAD

**Issue by DevJ5** [ossu/computer-science#604] opened 2019-09-19 19:56 UTC
Apparantly hack the kernel, i.e. [https://ops-class.org](url) is down.

Any substitute we can take is much appreciated.

**Comment by pachecohjr** [comment] 2019-09-19 20:18
https://web.archive.org/web/*/https://www.ops-class.org/

Plenty of snapshots for the site. Anything missing here?

**Comment by waciumawanjohi** [comment] 2019-09-19 21:23
This is a duplicate of https://github.com/ossu/computer-science/issues/602

Closing to keep conversation about this issue in one place.

**Closed by waciumawanjohi** 2019-09-19 21:23 UTC
