### ISSUE TITLE
Reliable Distributed Systems, Part 1 is "Not Currently Available"

### ISSUE THREAD

**Issue by s7oev** [ossu/computer-science#631] opened 2019-12-24 16:54 UTC
The course page says "Archived: Future Dates To Be Announced"; for some courses edX still allows to enroll to audit even after they are archived, but not this one. Weirdly, the second part of the series is one of those archived courses that you can still enroll to. But I am guessing that it wouldn't be of much use without Part 1. 

Links:
https://www.edx.org/course/reliable-distributed-algorithms-part-1
https://www.edx.org/course/reliable-distributed-algorithms-part-2

**Comment by waciumawanjohi** [comment] 2020-01-27 05:11
Duplicate of https://github.com/ossu/computer-science/issues/488

**Closed by waciumawanjohi** 2020-01-27 05:11 UTC
