### ISSUE TITLE
Change of policy for edx.org

### ISSUE THREAD

**Issue by thoqus** [ossu/computer-science#569] opened 2019-03-20 16:55 UTC
Since the beginning of the year most graded assignments in edx-courses can only be accessed after having paid for a certificate. :-(

In 6.00.1x Introduction to CS only the exams are not available. That is bad but not as bad as in some other courses where basically all assignments can't be accessed anymore. This seems to be the case for Software Construction: Data Abstraction from UBC. I think we should look for alternatives. Any ideas?

**Comment by suchov** [comment] 2019-03-21 08:55
:-(

**Comment by Divyangchauhan** [comment] 2019-03-22 09:21
What if the community itself develop course and exams based on already available material with permissible licenses. many course especially on ocw are under creative commons license we can use them and make courses that are available all the year.

**Comment by suchov** [comment] 2019-03-22 10:05
@Divyangchauhan it's quite time-consuming + it's quite difficult to compete with Harvard(CS50) MIT or Berkeley :)

**Comment by Divyangchauhan** [comment] 2019-03-23 07:09
I am not suggesting to create a mooc merely to archive the videos, slides and exercises and provide a way to test the solution probably by testing it with conditions.

**Comment by linkel** [comment] 2019-03-24 02:51
Yes, it's such a shame. I wanted to take How to Code: Simple Data and all of the questions I have encountered are locked except for the very first one. It's extremely discouraging, because when I took MIT 6.00.1x I had a blast with the finger exercises and I credit that course with helping me get started with learning programming last year. I am two weeks into my first software engineering position and it is amazing--it pains me that other students will not have access to the free material the same way that I was fortunate enough to have.

**Comment by Alaharon123** [comment] 2019-03-24 02:57
Does it not show the questions? It's self-graded so it shouldn't be grading for you anyway. If it's self-graded I should be grandfathered in and can post the questions

**Comment by linkel** [comment] 2019-03-24 03:03
No, I do not get to even view the questions. I'd love to even see them! It looks like this: 
![image](https://user-images.githubusercontent.com/7061807/54874331-82731200-4da6-11e9-8adf-eddd975f7739.png)

I've looked in some people's githubs but most people just post the solution in, and it is difficult to ascertain which goes with what. I may take the Coursera Programming Languages course in lieu of this, or perhaps look at materials listed on [the Racket list of courses](https://github.com/racket/racket/wiki/Courses-using-Racket) as an alternative.

**Comment by Alaharon123** [comment] 2019-03-24 04:14
I'm going to sleep rn, but I'll try and post the questions within a week. Ping me if I don't. Otherwise just read the book (How to Design Programs) and do its questions rather than the course. The idea isn't to learn Racket, but program design and whatnot; it just happens to use a limited version of Racket to do that.

**Comment by linkel** [comment] 2019-03-24 04:29
Oh nice. I did not realize there was a book that the course was based on. That's actually extremely helpful. Thank you. Yeah, I realize Racket is used as a tool in this course to reach a better understanding of writing programs--I'd grown excited to take this particular EdX course, so it was disappointing to witness the paywall firsthand.

**Comment by seanvert** [comment] 2019-03-31 19:46
> Oh nice. I did not realize there was a book that the course was based on. That's actually extremely helpful. Thank you. Yeah, I realize Racket is used as a tool in this course to reach a better understanding of writing programs--I'd grown excited to take this particular EdX course, so it was disappointing to witness the paywall firsthand.

I don't think it's a paywall, you can still use anything else to exercise those practices. The course is more about training designing data and code, I think it's even better to not have a lot of exercises because you have the liberty to do that in things you want to do. I'm using those things to write the data and logic of the sims in Haskell. The course is pretty good, I'm doing it and it's great.

If you're out of ideas try to simplifying any software you enjoy and exercise the contents on remaking this project.

**Comment by rtaibah** [comment] 2019-04-03 10:11
Seems like this is an issue with courses of UC San Diego and University of British Columbia only:

- [How to Code - Simple Data](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x)
- [How to Code - Complex Data](https://www.edx.org/course/how-code-complex-data-ubcx-htc2x)
- [Software Construction - Data Abstraction](https://www.edx.org/course/software-construction-data-abstraction-ubcx-softconst1x)
- [Software Construction - Object-Oriented Design](https://www.edx.org/course/software-construction-object-oriented-ubcx-softconst2x)
- [Computer Graphics](https://www.edx.org/course/computer-graphics)
- [Software Engineering: Introduction](https://www.edx.org/course/software-engineering-introduction-ubcx-softeng1x)
- [Software Development Capstone Project](https://www.edx.org/course/software-development-capstone-project-ubcx-softengprjx)

I guess suggesting alternatives would be a good idea?

**Comment by dropkickfish** [comment] 2019-04-05 18:48
re: How to Code questions being locked away

There is a way to access them through edX currently, but they're not immediately obvious. I've just started a new account to check.

![image](https://user-images.githubusercontent.com/33702528/55649714-a1789780-57db-11e9-91ba-5e24bb630b2c.png)
![image](https://user-images.githubusercontent.com/33702528/55649775-ce2caf00-57db-11e9-8b66-c4c106761eff.png)

**Comment by harshagarwalorg** [comment] 2019-04-28 08:57
I just made a GitHub account. This is my first post here.

I completed How to code: simple data with no problems. I had signed up for it back in December 2018 and completed it in April without having to pay.

I have now signed up for How to Code: Complex Data and I can confirm that the graded questions are not visible.

The $9 thing is also gone and you have to pay full price for the verified course to see the graded lecture questions after each video.

Note that if you look online you can find discount codes for 10% off and save yourself a few bucks.

I don't mind paying money to be honest, but free would have been preferable.

Anyways, thank you guys for creating the OSSU.

**Comment by seanvert** [comment] 2019-04-28 16:29
> Seems like this is an issue with courses of UC San Diego and University of British Columbia only:
> 
> * [How to Code - Simple Data](https://www.edx.org/course/how-code-simple-data-ubcx-htc1x)
> * [How to Code - Complex Data](https://www.edx.org/course/how-code-complex-data-ubcx-htc2x)
> * [Software Construction - Data Abstraction](https://www.edx.org/course/software-construction-data-abstraction-ubcx-softconst1x)
> * [Software Construction - Object-Oriented Design](https://www.edx.org/course/software-construction-object-oriented-ubcx-softconst2x)
> * [Computer Graphics](https://www.edx.org/course/computer-graphics)
> * [Software Engineering: Introduction](https://www.edx.org/course/software-engineering-introduction-ubcx-softeng1x)
> * [Software Development Capstone Project](https://www.edx.org/course/software-development-capstone-project-ubcx-softengprjx)
> 
> I guess suggesting alternatives would be a good idea?

  I was thinking about it, and I'm unsure about the legality of something like this, but I think it's doable to make some of our own community exercises to people doing those courses. I started something similar to that "Learn you a Haskell" book.

**Comment by ahmeed83** [comment] 2019-04-28 16:35
Why everyone wants everything for free these days?! I think it’s good that we pay for the people who made these wonderful courses. And if you don’t have the money then you can watch the videos for free.

**Comment by seanvert** [comment] 2019-04-28 16:38
> Why everyone wants everything for free these days?! I think it’s good that we pay for the people who made these wonderful courses. And if you don’t have the money then you can watch the videos for free.

Yes, there is also this. I don't feel inclined to add those kind of "features" to discourage people to pay for those courses. This is why I'm focusing on the Haskell book.

**Comment by keysler** [comment] 2019-05-04 10:53
> Why everyone wants everything for free these days?!
You are kinda quick on conclusions. For me, it isn't about the mere fact of content being free or paid — it's more about the price. 150$ — well, my monthly income has never been higher than 150$. But, as you've said:
> if you don’t have the money then you can watch the videos for free
We definitely can, though I think that the current paywall can be only the beginning of big changes to monetization system. Now we suffer only from limited access (1 month is very inconvenient for a lot of people, myself included), some time later we could completely lose it.
What I wanna propose is — maybe it's time to start archiving stuff? Not self-hosting, as someone said earlier, but only backup content and distribute it via bittorrent and/or whatever else that is more convenient.
Simple data, as I know, licensed under Creative Commons license, which allows for non-commercial redistribution. What do you guys think?

**Comment by ronminhnguyen** [comment] 2019-05-28 03:27
I'll chime in and say I just signed up for the 'How to Code- Simple Data' and they are no longer accepting new certificates (they are archiving the course in September). So there's no chance to see those practice problems.

Also to answer:
> re: How to Code questions being locked away
> 
> There is a way to access them through edX currently, but they're not immediately obvious. I've just started a new account to check.
> 

What you found are extra problem sets that are not part of the original lecture curriculum. I would agree that it seems we need substitutions for these classes (UBC classes at least)

**Comment by kenuxi** [comment] 2019-08-17 15:23
@dropkickfish Thanks for pointing that out. Cant believe I didnt see that. 
From here on we could just reupload those problem sets on Github and contribute on different ways of solving them. Probably the solutions are on  https://htdp.org aswell.

**Comment by pachecohjr** [comment] 2019-08-18 05:15
Hi all.

Yeah. It really disappoints me that edX has this new policy with all of their new courses. I'd be even more upset if they were limiting the activity on their archived courses, especially. Because of this, I will definitely make sure to log or save any quizzes and material that could possibly be removed later on.

My other concerns would be that if this is going to be done more strictly in the future, and with other platforms like Coursera. I understand they have to make some profit somewhere, but they all don't have to be done this way. College is already expensive enough.

**Comment by pachecohjr** [comment] 2019-08-18 05:20
Hi all.

Yeah. It really disappoints me that edX has this new policy with all of their new courses. I'd be even more upset if they were limiting the activity on their archived courses, especially. Because of this, I will definitely make sure to log or save any quizzes and material that could possibly be removed later on.

My other concerns would be that if this is going to be done more strictly in the future, and with other platforms like Coursera. I understand they have to make some profit somewhere, but they all don't have to be done this way. College is already expensive enough.

So, if I understand correctly: (most of) the edX courses labeled as "Active" give a free Audit period now when you select the course (and select to Audit the course), and after that period, it's over? Or is it that the while the course is open and active and not archived, is when you can audit the course for free? (Or is it both?) I'm confused. Would it make it any difference if I re-created a dummy account for active courses to which my audit trial has ended?

**Comment by pachecohjr** [comment] 2019-08-18 05:22
Hi all.

Yeah. It really disappoints me that edX has this new policy with all of their new courses. I'd be even more upset if they were limiting the activity on their archived courses, especially. Because of this, I will definitely make sure to log or save any quizzes and material that could possibly be removed later on.

My other concerns would be that if this is going to be done more strictly in the future, and with other platforms like Coursera. I understand they have to make some profit somewhere, but they all don't have to be done this way. College is already expensive enough. I have also come to learn to save everything taught in my college courses because some of my previous professors have had noteworthy material and would remove or delete their lectures after a semester.

So, if I understand correctly: (most of) the edX courses labeled as "Active" give a free Audit period now when you select the course (and select to Audit the course), and after that period, it's over? Or is it that the while the course is open and active and not archived, is when you can audit the course for free? (Or is it both?) I'm confused. Would it make it any difference if I re-created a dummy account for active courses to which my audit trial has ended?

**Comment by keysler** [comment] 2019-09-02 19:02
> (most of) the edX courses labeled as "Active" give a free Audit period now when you select the course (and select to Audit the course), and after that period, it's over

That's right

> Would it make it any difference if I re-created a dummy account for active courses to which my audit trial has ended?

It worked for me.

**Comment by seanvert** [comment] 2019-09-04 10:54
I think it is possible to download all the video lectures in one go. https://github.com/coursera-dl/edx-dl

Then you can just get all the assignments and take all the tests.

**Comment by waciumawanjohi** [comment] 2020-01-26 19:57
Closing this issue as there have been no new comments in 15 months.

**Closed by waciumawanjohi** 2020-01-26 19:57 UTC
