### ISSUE TITLE
Assignment 3 Link for Computer Networking not available

### ISSUE THREAD

**Issue by rodrigomlp** [ossu/computer-science#598] opened 2019-09-03 07:33 UTC
I am going to start my journey in learning more about computer networking. However, the Assignment 3 link is not available. Can someone point me in the right direction?

Cheers

**Comment by waciumawanjohi** [comment] 2019-09-03 09:22
Hmm! It seems to have recently disappeared.
If you put the link into the wayback machine, you'll find archived copies of the pdf.
https://archive.org/web/

I'll update the link.

**Comment by xxylem** [comment] 2019-09-03 14:02
I just found [these assignments on the Mininet Wiki.](https://github.com/mininet/mininet/wiki/Teaching-and-Learning-with-Mininet). Apparently they are based on the programming assignments in the Stanford Computer Networking course. They use the Mininet environment, so it may be more intuitive to use (?). I haven't done the assigments either way yet though, so I'm not sure.

Mininet is available [here.](http://mininet.org/download/)
A walkthrough is available [here.](http://mininet.org/walkthrough/)

Maybe it's worth a try?

**Comment by waciumawanjohi** [comment] 2019-09-04 01:45
Hey @xxylem ,
We're always happy to hear about new resources that have been located. To meet the computer networks requirements of an undergraduate degree we need 4 assignments that target a few specific competencies. You can read more about that in this issue: https://github.com/ossu/computer-science/issues/520#issuecomment-515740803

If you think that one of these mininet assignments is a good replacement for the current assignments, can you give a quick write up on that?

**Comment by xxylem** [comment] 2019-09-04 08:38
@waciumawanjohi 
I went looking for this because the [Stanford assignment](https://www.scs.stanford.edu/10au-cs144/lab/reliable/reliable.html#getting-started) seems to assume access to "a machine managed by Stanford ITSS", specifically the Myth cluster. Having said that, I haven't started the assignment properly yet, so it may be possible without...

The Mininet assignments essentially emulate this network environment on a single PC not in the Stanford network. The problem is that labs 3, 4 & 5 are covered by the mininet assignments, but not the one listed on OSSU (Lab 1 & 2). Unfortunately, these assignments do not exactly line-up with the curriculum requirements, but perhaps it is better to have a slightly different assignment that if the Stanford one turns out not to be possible.

Anyway, I am going to try all of the assignments (Stanford, Princeton, Mininet) over the next week or so and see what is/is not doable. Then I'll let you know.

**Comment by waciumawanjohi** [comment] 2019-09-04 16:15
@xxylem, I look forward to hearing your assessment!

**Comment by waciumawanjohi** [comment] 2019-09-08 18:51
Original issue fixed in https://github.com/ossu/computer-science/pull/601

@xxylem , when you are ready, can you add your thoughts about the Computer Network assignments to this issue: https://github.com/ossu/computer-science/issues/520

**Closed by waciumawanjohi** 2019-09-08 18:51 UTC
